[2025-08-24T14:08:11.372+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-24T14:08:11.394+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_bolsa_familia.extract_bronze scheduled__2025-08-23T00:00:00+00:00 [queued]>
[2025-08-24T14:08:11.399+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_bolsa_familia.extract_bronze scheduled__2025-08-23T00:00:00+00:00 [queued]>
[2025-08-24T14:08:11.400+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-08-24T14:08:11.728+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): extract_bronze> on 2025-08-23 00:00:00+00:00
[2025-08-24T14:08:11.733+0000] {standard_task_runner.py:64} INFO - Started process 111 to run task
[2025-08-24T14:08:11.736+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_bolsa_familia', 'extract_bronze', 'scheduled__2025-08-23T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_bolsa_familia.py', '--cfg-path', '/tmp/tmpnween5ik']
[2025-08-24T14:08:11.738+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask extract_bronze
[2025-08-24T14:08:11.799+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_bolsa_familia.extract_bronze scheduled__2025-08-23T00:00:00+00:00 [running]> on host 71cf75a943db
[2025-08-24T14:08:11.945+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rayane' AIRFLOW_CTX_DAG_ID='etl_bolsa_familia' AIRFLOW_CTX_TASK_ID='extract_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-08-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-23T00:00:00+00:00'
[2025-08-24T14:08:11.946+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-24T14:08:11.963+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-24T14:08:11.964+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/airflow/apps/extracao_dados_api_bronze.py']
[2025-08-24T14:08:11.974+0000] {subprocess.py:86} INFO - Output:
[2025-08-24T14:08:12.041+0000] {subprocess.py:93} INFO - python: can't open file '/opt/airflow/apps/extracao_dados_api_bronze.py': [Errno 2] No such file or directory
[2025-08-24T14:08:12.046+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-24T14:08:12.047+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-24T14:08:12.054+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-24T14:08:12.059+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_bolsa_familia, task_id=extract_bronze, run_id=scheduled__2025-08-23T00:00:00+00:00, execution_date=20250823T000000, start_date=20250824T140811, end_date=20250824T140812
[2025-08-24T14:08:12.081+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task extract_bronze (Bash command failed. The command returned a non-zero exit code 2.; 111)
[2025-08-24T14:08:12.115+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-24T14:08:12.132+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-24T14:08:12.142+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
