[2025-08-24T14:08:15.478+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-24T14:08:15.502+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_bolsa_familia.extract_bronze manual__2025-08-24T14:03:07.436261+00:00 [queued]>
[2025-08-24T14:08:15.507+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_bolsa_familia.extract_bronze manual__2025-08-24T14:03:07.436261+00:00 [queued]>
[2025-08-24T14:08:15.509+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-08-24T14:08:15.526+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): extract_bronze> on 2025-08-24 14:03:07.436261+00:00
[2025-08-24T14:08:15.531+0000] {standard_task_runner.py:64} INFO - Started process 121 to run task
[2025-08-24T14:08:15.538+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_bolsa_familia', 'extract_bronze', 'manual__2025-08-24T14:03:07.436261+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_bolsa_familia.py', '--cfg-path', '/tmp/tmpzcf8vff0']
[2025-08-24T14:08:15.540+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask extract_bronze
[2025-08-24T14:08:15.593+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_bolsa_familia.extract_bronze manual__2025-08-24T14:03:07.436261+00:00 [running]> on host 71cf75a943db
[2025-08-24T14:08:15.650+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rayane' AIRFLOW_CTX_DAG_ID='etl_bolsa_familia' AIRFLOW_CTX_TASK_ID='extract_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-08-24T14:03:07.436261+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-24T14:03:07.436261+00:00'
[2025-08-24T14:08:15.651+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-24T14:08:15.669+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-24T14:08:15.671+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/airflow/apps/extracao_dados_api_bronze.py']
[2025-08-24T14:08:15.680+0000] {subprocess.py:86} INFO - Output:
[2025-08-24T14:08:15.756+0000] {subprocess.py:93} INFO - python: can't open file '/opt/airflow/apps/extracao_dados_api_bronze.py': [Errno 2] No such file or directory
[2025-08-24T14:08:15.760+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-24T14:08:15.761+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-24T14:08:15.766+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-24T14:08:15.771+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_bolsa_familia, task_id=extract_bronze, run_id=manual__2025-08-24T14:03:07.436261+00:00, execution_date=20250824T140307, start_date=20250824T140815, end_date=20250824T140815
[2025-08-24T14:08:15.787+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task extract_bronze (Bash command failed. The command returned a non-zero exit code 2.; 121)
[2025-08-24T14:08:15.798+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-24T14:08:15.816+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-24T14:08:16.129+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
